[package]
name = "clownlib_proc_macro_support"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.67"
quote = "1.0.33"
synstructure = "0.13.0"
syn = { version = "2.0.37", features = ["full"] }
