[workspace]
resolver = "2"
members = [
  "clowncc_lex",
  "clowncc_macros",
  "clowncc_parse",
  "clowncc_token",
  "clowncc_version",
  "clownlib_proc_macro_support",
  "clownlib_static_assert",
  "clownlib_std_ext",
]
